In [217]:
from ucimlrepo import fetch_ucirepo
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression, Ridge, Lasso
from sklearn.metrics import r2_score
from sklearn.preprocessing import PolynomialFeatures
from sklearn.pipeline import Pipeline
from ucimlrepo import fetch_ucirepo

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, MinMaxScaler


In [219]:
concrete_compressive_strength = fetch_ucirepo(id=165)

# data (as pandas dataframes)
X = concrete_compressive_strength.data.features
y = concrete_compressive_strength.data.targets


In [220]:
X_train, X_test, y_train, y_test = train_test_split(X,y, random_state = 24, test_size = 0.3)

In [221]:
lr = LinearRegression()
lr.fit(X_train,y_train)

print(lr.intercept_,lr.coef_)



[-35.44918333] [[ 0.12726535  0.11257926  0.09835135 -0.13691381  0.23733402  0.02020436
   0.02616505  0.12251105]]


In [222]:
y_pred = lr.predict(X_test)

In [223]:
X_train, X_test, y_train, y_test = train_test_split(X,y, random_state = 24, test_size = 0.3)

In [224]:
#With MINMAX Scaling

In [225]:
scl_std = StandardScaler()
pipe = Pipeline([('SCL',scl_std),('LR',lr)])
pipe.fit(X_train,y_train)
y_pred = pipe.predict(X_test)
r2_score(y_test,y_pred)

0.5771752777048791

In [226]:
poly = PolynomialFeatures(degree = 2,include_bias = False).set_output(transform='pandas')
scl_std = StandardScaler()
pipe = Pipeline([('SCL',scl_std),('POLY',poly),('LR',lr)])
pipe.fit(X_train,y_train)
y_pred = pipe.predict(X_test)
r2_score(y_test,y_pred)

0.7807023265206907

In [227]:
ridge = Ridge()
ridge.fit(X,y)
ridge.intercept_,ridge.coef_

(array([-23.32957301]),
 array([[ 0.11980439,  0.10386586,  0.08793476, -0.14992243,  0.2922038 ,
          0.01808557,  0.0201901 ,  0.11422205]]))

In [228]:
lr = LinearRegression()
lr.fit(X,y)
lr.intercept_, lr.coef_

(array([-23.33121358]),
 array([[ 0.11980433,  0.10386581,  0.08793432, -0.14991842,  0.2922246 ,
          0.01808621,  0.02019035,  0.11422207]]))

In [229]:
y_pred = lr.predict(X_test)
r2_score(y_test,y_pred)

0.5884767547970231

In [230]:
ridge.fit(X_train,y_train)
y_pred = ridge.predict(X_test)
r2_score(y_test,y_pred)

0.5771749099675626

In [231]:
poly = PolynomialFeatures(degree = 3,include_bias = False).set_output(transform='pandas')
X_poly_trn = poly.fit_transform(X_train)
X_poly_tst = poly.transform(X_test)
ridge.fit(X_poly_trn,y_train)
y_pred = ridge.predict(X_poly_tst)
r2_score(y_test,y_pred)

C:\Users\dai.STUDENTSDC\AppData\Local\anaconda3\Lib\site-packages\sklearn\linear_model\_ridge.py:204: LinAlgWarning: Ill-conditioned matrix (rcond=9.96075e-21): result may not be accurate.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T


0.8695065063191985

In [232]:
# Filtered the extracted features based on coefficient values

In [233]:
df_coef = pd.DataFrame({'col_names': list(X_poly_trn.columns),'coef':list(ridge.coef_[0])})
print(df_coef.shape)
df_coef[df_coef['coef'] > 0.0001]

(164, 2)


col_names      coef
1                           Blast Furnace Slag  0.636144
5                             Coarse Aggregate  2.612272
6                               Fine Aggregate  0.909094
7                                          Age  0.123618
8                                     Cement^2  0.010445
9                    Cement Blast Furnace Slag  0.031224
10                              Cement Fly Ash  0.008666
14                       Cement Fine Aggregate  0.023399
16                        Blast Furnace Slag^2  0.004927
17                  Blast Furnace Slag Fly Ash  0.015132
18                    Blast Furnace Slag Water  0.011398
19         Blast Furnace Slag Superplasticizer  0.108260
21           Blast Furnace Slag Fine Aggregate  0.040342
22                      Blast Furnace Slag Age  0.016544
24                               Fly Ash Water  0.021236
25                    Fly Ash Superplasticizer  0.288636
27                      Fly Ash Fine Aggregate  0.050909
31                      Water Coarse Aggregate  0.020078
32                        Water Fine Aggregate  0.010407
33                                   Water Age  0.016039
35           Superplasticizer Coarse Aggregate  0.357927
37                        Superplasticizer Age  0.601483
38                          Coarse Aggregate^2  0.004922
42                          Fine Aggregate Age  0.010530
43                                       Age^2  0.001606
66               Cement Water Superplasticizer  0.000638
70                   Cement Superplasticizer^2  0.000930
94   Blast Furnace Slag Water Superplasticizer  0.000233
98       Blast Furnace Slag Superplasticizer^2  0.000221
115             Fly Ash Water Superplasticizer  0.000591
119                 Fly Ash Superplasticizer^2  0.001580
130                   Water^2 Superplasticizer  0.001146
136      Water Superplasticizer Fine Aggregate  0.000637
146          Superplasticizer^2 Fine Aggregate  0.000393
147                     Superplasticizer^2 Age  0.000688

In [234]:
df_coef

col_names          coef
0                    Cement -2.713694e+00
1        Blast Furnace Slag  6.361436e-01
2                   Fly Ash -2.191047e+00
3                     Water -1.489495e-01
4          Superplasticizer -3.224595e-02
..                      ...           ...
159  Coarse Aggregate Age^2  4.982096e-07
160        Fine Aggregate^3  6.025196e-07
161    Fine Aggregate^2 Age -4.991126e-06
162    Fine Aggregate Age^2 -3.874725e-06
163                   Age^3  4.368270e-06

[164 rows x 2 columns]

In [240]:
print(ridge.coef_)

[[-2.71369370e+00  6.36143557e-01 -2.19104687e+00 -1.48949528e-01
  -3.22459488e-02  2.61227210e+00  9.09094082e-01  1.23618480e-01
   1.04451224e-02  3.12236342e-02  8.66605537e-03 -1.73567888e-02
  -7.42857148e-02 -1.64249699e-02  2.33994125e-02 -4.52764597e-03
   4.92733932e-03  1.51316208e-02  1.13976755e-02  1.08260044e-01
  -4.35844961e-02  4.03424911e-02  1.65439810e-02 -3.37890818e-02
   2.12356041e-02  2.88636317e-01 -3.78369592e-02  5.09089174e-02
  -5.32041881e-03 -2.30583708e-02 -1.11741016e+00  2.00777909e-02
   1.04069153e-02  1.60386889e-02 -3.23959572e-01  3.57926884e-01
  -2.09066877e-01  6.01483221e-01  4.92214122e-03 -1.11664061e-02
  -1.04666932e-02 -3.84180728e-04  1.05299930e-02  1.60574796e-03
  -1.64009969e-06 -8.64560240e-06 -3.67881935e-06 -1.01479370e-05
  -2.68947401e-05  1.96601616e-07 -8.83725261e-06  3.56594248e-06
  -8.78262754e-06 -1.39706510e-05 -3.44696684e-05 -8.66901527e-05
   3.56414984e-06 -2.86023493e-05  3.59882664e-07  1.65247841e-05
  -1.96374

In [246]:
#considering Different values of Alpha

In [253]:
ridge = Ridge(alpha=0.22)
ridge.fit(X_train,y_train)
y_pred = ridge.predict(X_test)
r2_score(y_test,y_pred)

0.5771751967997472

In [255]:
# Tuning for Alpha = [0.01,0.1,0.3,0.6,1,1.5,2,4,10]

In [257]:
alphas = [0.01,0.1,0.3,0.6,1,1.5,2,4,10]
scores = []
for a in alphas:
    ridge = Ridge(alpha=a)
    ridge.fit(X_train,y_train)
    y_pred = ridge.predict(X_test)
    scores.append(r2_score(y_test, y_pred))
print(scores)    



[0.5771752740273375, 0.5771752409296147, 0.5771751673801079, 0.5771750570584018, 0.5771749099675626, 0.5771747261116779, 0.5771745422643093, 0.5771738069600134, 0.5771716018651836]


In [262]:
np.max(scores)

0.5771752740273375

In [264]:
np.argmax(scores)

0

In [266]:
i_max = np.argmax(scores)
print("Best Alpha:",alphas[i_max])
print("Best Score:",scores[i_max])

Best Alpha: 0.01
Best Score: 0.5771752740273375


In [268]:
# generate alpha values

In [270]:
np.linspace(0.0001,10,20)

array([1.00000000e-04, 5.26410526e-01, 1.05272105e+00, 1.57903158e+00,
       2.10534211e+00, 2.63165263e+00, 3.15796316e+00, 3.68427368e+00,
       4.21058421e+00, 4.73689474e+00, 5.26320526e+00, 5.78951579e+00,
       6.31582632e+00, 6.84213684e+00, 7.36844737e+00, 7.89475789e+00,
       8.42106842e+00, 8.94737895e+00, 9.47368947e+00, 1.00000000e+01])

In [272]:
alphas = np.linspace(0.0001,10,20)
scores = []
for a in alphas:
    ridge = Ridge(alpha=a)
    ridge.fit(X_train,y_train)
    y_pred = ridge.predict(X_test)
    scores.append(r2_score(y_test, y_pred))
print(scores)    



[0.5771752776681036, 0.5771750841198391, 0.5771748905810096, 0.5771746970516156, 0.577174503531658, 0.5771743100211375, 0.5771741165200551, 0.5771739230284114, 0.5771737295462072, 0.5771735360734433, 0.5771733426101202, 0.5771731491562393, 0.5771729557118006, 0.577172762276805, 0.5771725688512538, 0.577172375435147, 0.577172182028486, 0.5771719886312712, 0.5771717952435036, 0.5771716018651836]


In [273]:
np.max(scores)

0.5771752776681036

In [276]:
np.argmax(scores)

0

In [278]:
i_max = np.argmax(scores)
print("Best Alpha:",alphas[i_max])
print("Best Score:",scores[i_max])

Best Alpha: 0.0001
Best Score: 0.5771752776681036


In [291]:
# hyper parameter Optimization #Lasso Regresssion

In [293]:
alphas = np.linspace(0.0001,10,20)
scores = []
for a in alphas:
    lasso = Lasso(alpha=a)
    lasso.fit(X_train,y_train)
    y_pred = lasso.predict(X_test)
    scores.append(r2_score(y_test, y_pred))
print(scores)    



[0.5771752162488388, 0.5767887675592975, 0.5762767463931009, 0.5756396636831074, 0.574877359379247, 0.5739906651543902, 0.572979464363941, 0.5721009707960271, 0.5722614778993542, 0.5724099561568741, 0.572544735498197, 0.5726666359648799, 0.5727764086956115, 0.5728731096945463, 0.5729565781568045, 0.5730274603207464, 0.573085805075227, 0.5731315172304163, 0.5731560475699367, 0.5731618042353835]


In [295]:
i_max = np.argmax(scores)
print("Best Alpha:",alphas[i_max])
print("Best Score:",scores[i_max])

Best Alpha: 0.0001
Best Score: 0.5771752162488388
