In [30]:
import numpy as np
from sklearn.preprocessing import StandardScaler
import pandas as pd

In [32]:
a = np.array([90,34,89,57,89,23,64])
b = np.array([1,4,3,2,5,1,4])

In [34]:
ma, mb = a.mean() , b.mean()

In [36]:
sa, sb = a.std(), b.std()

In [38]:
scl_a = (a - ma)/sa

In [40]:
scl_b = (b - mb)/sb

In [42]:
(ma, sa), (scl_a.mean(),scl_a.std())

((63.714285714285715, 25.510302040628247),
 (-5.551115123125783e-17, 0.9999999999999999))

In [44]:
(mb,sb), (scl_b.mean(), scl_b.std())

((2.857142857142857, 1.456862718169367), (-4.7580986769649563e-17, 1.0))

In [46]:
#Using Standard Scaler()

In [49]:
scl_std = StandardScaler()
df = pd.DataFrame({'a': a, 'b': b})
scl_std.fit(df)


StandardScaler()

In [55]:
print(scl_std.mean_)

[63.71428571  2.85714286]


In [57]:
ma,mb

(63.714285714285715, 2.857142857142857)

In [61]:
scl_std.scale_


array([25.51030204,  1.45686272])

In [63]:
sa , sb

(25.510302040628247, 1.456862718169367)

In [65]:
scl_std.transform(df)


array([[ 1.03039604, -1.27475488],
       [-1.16479553,  0.78446454],
       [ 0.99119619,  0.09805807],
       [-0.26319899, -0.58834841],
       [ 0.99119619,  1.47087101],
       [-1.59599387, -1.27475488],
       [ 0.01119996,  0.78446454]])

In [67]:
scl_a, scl_b

(array([ 1.03039604, -1.16479553,  0.99119619, -0.26319899,  0.99119619,
        -1.59599387,  0.01119996]),
 array([-1.27475488,  0.78446454,  0.09805807, -0.58834841,  1.47087101,
        -1.27475488,  0.78446454]))

In [85]:

# Min max Scaling
# Algo for DNN, Vision (open cv)

a,b


(array([90, 34, 89, 57, 89, 23, 64]), array([1, 4, 3, 2, 5, 1, 4]))

In [87]:
mn_a, mn_b , mx_a, mx_b = a.min(), b.min(), a.max(), b.max()

In [89]:
print(mn_a,mn_b,mx_a,mx_b)

23 1 90 5


In [91]:
scl_a = (a - mn_a) / (mx_a - mn_a)
scl_b = (b - mn_b) / (mx_b - mn_b)

In [93]:
scl_a ,scl_b

(array([1.        , 0.1641791 , 0.98507463, 0.50746269, 0.98507463,
        0.        , 0.6119403 ]),
 array([0.  , 0.75, 0.5 , 0.25, 1.  , 0.  , 0.75]))