In [116]:

import pandas as pd
import numpy as np
from sklearn.metrics import r2_score
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import PolynomialFeatures
from sklearn.impute import SimpleImputer
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score
from sklearn.linear_model import ElasticNet
from sklearn.metrics import mean_squared_error
from sklearn.model_selection import GridSearchCV
from sklearn.linear_model import LogisticRegression

from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import LabelEncoder
from sklearn.compose import make_column_transformer
from sklearn.compose import make_column_selector


In [118]:
default = pd.read_csv("Default.csv")

In [120]:
default.columns

Index(['default', 'student', 'balance', 'income'], dtype='object')

In [122]:
default.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype  
---  ------   --------------  -----  
 0   default  10000 non-null  object 
 1   student  10000 non-null  object 
 2   balance  10000 non-null  float64
 3   income   10000 non-null  float64
dtypes: float64(2), object(2)
memory usage: 312.6+ KB


In [124]:
X = default.drop('default',axis=1)
y = default['default']

In [140]:
from sklearn.preprocessing import OneHotEncoder
ohe = OneHotEncoder(sparse_output = False, drop = 'first').set_output(transform = 'pandas')
# to change it into pandas

ct = make_column_transformer(('passthrough',make_column_selector(dtype_exclude=object)),(ohe,make_column_selector(dtype_include = object)),verbose_feature_names_out = False).set_output(transform='pandas')
lr = LogisticRegression()
pipe = Pipeline([('CT',ct),('LR',lr)])
pipe.fit(X_train,y_train)
y_pred = pipe.predict(X_test)
print(accuracy_score(y_test,y_pred))

0.97


In [78]:
dum_X = ohe.fit_transform(X) #will return numpy array by default

In [80]:
lbl = LabelEncoder()
default['default'] = lbl.fit_transform(default['default'])

In [81]:
lbl = LabelEncoder()
default['student'] = lbl.fit_transform(default['student'])

In [84]:
lbl.classes_

array([0, 1])

In [86]:
y.value_counts()

default
0    9667
1     333
Name: count, dtype: int64

In [88]:
X_train, X_test, y_train, y_test = train_test_split(X,y,random_state = 24, test_size = 0.3)

In [90]:
lr = LogisticRegression()
lr.fit(X_train,y_train)
y_pred = lr.predict(X_test)

lr.coef_

array([[-3.39547361e-01,  5.90050679e-03,  1.10698187e-05]])

In [92]:
y_test.shape

(3000,)

In [94]:
# Naive Rule/ Baseline Model

In [100]:
y_pred = np.zeros(y_test.shape[0])
y_pred

array([0., 0., 0., ..., 0., 0., 0.])

In [102]:
y_test.value_counts()

default
0    2901
1      99
Name: count, dtype: int64

In [106]:
print(confusion_matrix(y_test,y_pred))

[[2901    0]
 [  99    0]]


In [108]:
accuracy_score(y_test, y_pred)

0.967

In [110]:
# ML Model

In [112]:
y_pred = lr.predict(X_test)

In [123]:
accuracy_score(y_test, y_pred)

0.9777777777777777

In [ ]:
# KFold CV


In [138]:
#y_pred_nv = np.repeat("No",y_test.shape[0])
#print(accuracy_score(y_test,y_pred_nv))

In [134]:
results = cross_val_score(pipe,X,y)
results.mean()

0.9731