In [1]:

import pandas as pd
import numpy as np
from sklearn.metrics import r2_score
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import PolynomialFeatures
from sklearn.impute import SimpleImputer
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score
from sklearn.linear_model import ElasticNet
from sklearn.metrics import mean_squared_error
from sklearn.model_selection import GridSearchCV
from sklearn.linear_model import LogisticRegression

from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import LabelEncoder



In [2]:
iris = pd.read_csv("iris.csv")

In [3]:
iris.columns

Index(['Sepal.Length', 'Sepal.Width', 'Petal.Length', 'Petal.Width',
       'Species'],
      dtype='object')

In [4]:
iris.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   Sepal.Length  150 non-null    float64
 1   Sepal.Width   150 non-null    float64
 2   Petal.Length  150 non-null    float64
 3   Petal.Width   150 non-null    float64
 4   Species       150 non-null    object 
dtypes: float64(4), object(1)
memory usage: 6.0+ KB


In [5]:
lbl = LabelEncoder()
iris['Species'] = lbl.fit_transform(iris['Species'])

In [6]:
lbl.classes_

array(['setosa', 'versicolor', 'virginica'], dtype=object)

In [7]:
y = iris['Species']
X = iris.drop('Species',axis =1)

In [8]:
y.value_counts()

Species
0    50
1    50
2    50
Name: count, dtype: int64

In [9]:
X_train, X_test, y_train, y_test = train_test_split(X,y,random_state = 24, test_size = 0.3)

In [10]:
lr = LogisticRegression()
lr.fit(X_train,y_train)
y_pred = lr.predict(X_test)

lr.coef_

array([[-0.47289138,  0.88068018, -2.28377202, -0.96398012],
       [ 0.52210076, -0.28184099, -0.12835638, -0.90568307],
       [-0.04920938, -0.5988392 ,  2.4121284 ,  1.86966319]])

In [11]:
y_test.shape

(45,)

In [12]:
# Naive Rule/ Baseline Model

In [13]:
y_pred = np.repeat(2,y_test.shape[0])
y_pred

array([2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2])

In [14]:
y_test.value_counts()

Species
2    18
0    15
1    12
Name: count, dtype: int64

In [15]:
print(confusion_matrix(y_test,y_pred))

[[ 0  0 15]
 [ 0  0 12]
 [ 0  0 18]]


In [16]:
accuracy_score(y_test, y_pred)

0.4

In [17]:
# ML Model

In [18]:
y_pred = lr.predict(X_test)

In [19]:
accuracy_score(y_test, y_pred)

0.9777777777777777

In [20]:
## Any Ml Model score should be better than score of baseline model.
# Here baseline(naive) model score = 0.4  & ML model Score = 0.9777777777777777.
# Hence we can say that this ML model can be a relevant model.