In [44]:
from ucimlrepo import fetch_ucirepo 

In [138]:

import pandas as pd
import numpy as np
from sklearn.metrics import r2_score
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import PolynomialFeatures
from sklearn.impute import SimpleImputer
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score
from sklearn.linear_model import ElasticNet
from sklearn.metrics import mean_squared_error
from sklearn.model_selection import GridSearchCV
from sklearn.linear_model import LogisticRegression

from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score


In [140]:
pip install ucimlrepo

Note: you may need to restart the kernel to use updated packages.


In [141]:

  
# fetch dataset 
breast_cancer_wisconsin_original = fetch_ucirepo(id=15) 
  
# data (as pandas dataframes) 
X = breast_cancer_wisconsin_original.data.features 
y = breast_cancer_wisconsin_original.data.targets 
  
X.columns

Index(['Clump_thickness', 'Uniformity_of_cell_size',
       'Uniformity_of_cell_shape', 'Marginal_adhesion',
       'Single_epithelial_cell_size', 'Bare_nuclei', 'Bland_chromatin',
       'Normal_nucleoli', 'Mitoses'],
      dtype='object')

In [142]:
y['Class'].unique()

array([2, 4], dtype=int64)

In [143]:
X.isnull().sum()

Clump_thickness                 0
Uniformity_of_cell_size         0
Uniformity_of_cell_shape        0
Marginal_adhesion               0
Single_epithelial_cell_size     0
Bare_nuclei                    16
Bland_chromatin                 0
Normal_nucleoli                 0
Mitoses                         0
dtype: int64

In [144]:
X.drop('Bare_nuclei',axis =1,inplace = True)

C:\Users\dai\AppData\Local\Temp\ipykernel_1604\1774896237.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X.drop('Bare_nuclei',axis =1,inplace = True)


In [145]:
X.isnull().sum().sum()

0

In [146]:
y['Class'].value_counts()

Class
2    458
4    241
Name: count, dtype: int64

In [147]:
y['Class'] = np.where(y['Class']==2,0,1)


C:\Users\dai\AppData\Local\Temp\ipykernel_1604\2243808073.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  y['Class'] = np.where(y['Class']==2,0,1)


In [148]:
X_train, X_test, y_train, y_test = train_test_split(X,y,random_state = 24, test_size = 0.3)

In [149]:
lr = LogisticRegression()
lr.fit(X_train,y_train)
lr.coef_

C:\Users\dai.STUDENTSDC\AppData\Local\anaconda3\Lib\site-packages\sklearn\utils\validation.py:1300: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


array([[0.46898081, 0.19373096, 0.61145965, 0.19844095, 0.05204591,
        0.54456409, 0.12560554, 0.43702294]])

In [150]:
y_pred = lr.predict(X_test)

In [151]:
print("y_test",y_test['Class'].values)
print("y_pred:\n",y_pred)



y_test [0 1 1 1 1 0 1 0 0 0 1 1 1 0 0 0 0 1 1 1 0 0 1 0 0 1 0 0 0 0 1 1 0 0 0 0 0
 1 0 0 0 0 0 0 1 0 1 1 1 0 0 0 1 0 0 0 0 1 0 0 1 0 1 0 0 1 1 0 0 1 0 0 0 0
 0 0 0 1 0 0 0 0 0 1 0 0 1 0 0 0 0 1 1 1 0 0 0 1 0 0 1 0 1 0 1 1 0 1 1 1 1
 0 0 0 0 1 0 0 1 0 1 0 0 1 0 0 0 0 0 0 0 0 0 1 1 0 1 0 1 0 1 0 1 0 0 0 0 1
 0 1 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 1 0 0 0 0 0 0 1 0 1 0
 0 1 1 1 0 1 0 0 1 1 0 1 1 0 0 1 0 1 0 0 0 1 0 0 1]
y_pred:
 [0 1 1 1 1 0 1 0 0 0 1 1 1 0 0 0 0 1 1 1 0 0 1 0 0 1 0 0 0 0 1 1 0 0 0 0 0
 1 0 0 0 0 0 0 1 0 1 1 1 0 0 0 1 0 0 0 0 1 0 0 1 0 1 0 0 1 1 0 0 1 0 0 0 0
 0 0 0 1 0 0 0 0 0 1 0 0 1 0 0 0 0 1 1 1 0 0 0 1 0 0 1 0 0 0 1 1 0 1 1 1 1
 0 0 0 0 1 0 0 1 0 1 0 0 1 0 0 0 0 0 0 0 0 0 1 1 0 1 0 1 0 1 0 0 0 0 0 0 1
 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 0 1 0 0 0 0 0 0 1 0 1 0
 0 1 1 1 0 1 1 0 1 1 0 1 1 0 0 1 0 1 0 1 0 0 0 0 1]


In [178]:
#pd.crosstab(y_test['Class'].values,y_pred)
#0->0 1->1 correct prediction 0->1 1 1->0 wrong prediction
#confusion matrix

In [180]:
203/210 
#(135+68)/135+68+3+4
#accuracy score

0.9666666666666667

In [182]:
print(confusion_matrix(y_test['Class'],y_pred))

[[135   3]
 [  4  68]]


In [184]:
accuracy_score(y_test['Class'], y_pred)

0.9666666666666667

In [192]:
y['Class'].value_counts(normalize = True)


Class
0    0.655222
1    0.344778
Name: proportion, dtype: float64

In [196]:
# Naive rule/Baseline Model

In [202]:
y_pred = np.zeros(210)

In [204]:
accuracy_score(y_test['Class'], y_pred)

0.6571428571428571

In [208]:
# Any Ml Model score should be better than score of baseline model.
# Here baseline(naive) model score = 0.6571428571428571  & ML model Score = 0.9666666666666667.
# Hence we can say that this ML model can be a relevant model.